version: '3'

x-zookeeper-common:
  &zookeeper-common
  image: confluentinc/cp-zookeeper:6.2.0
  environment:
    &zookeeper-common-env
    ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: 24
    ZOOKEEPER_AUTOPURGE_SNAP_RETAIN_COUNT: 3
    ZOOKEEPER_DATA_DIR: /var/lib/zookeeper/
    ZOOKEEPER_INIT_LIMIT: 5
    ZOOKEEPER_MAX_CLIENT_CNXNS: 0
    ZOOKEEPER_SERVERS: localhost:22888:23888;localhost:32888:33888;localhost:42888:43888
    ZOOKEEPER_SYNC_LIMIT: 2
    ZOOKEEPER_TICK_TIME: 2000
  network_mode: host

x-kafka-common:
  &kafka-common
  image: confluentinc/cp-kafka:6.2.0
  environment:
    &kafka-common-env
    KAFKA_DEFAULT_REPLICATION_FACTOR: 3
    KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
    # KAFKA_LOG_DIRS: /var/lib/kafka/data
    KAFKA_LOG_RETENTION_HOURS: 168
    KAFKA_MIN_INSYNC_REPLICAS: 2
    KAFKA_NUM_PARTITIONS: 3
    KAFKA_ZOOKEEPER_CONNECT: localhost:22181,localhost:32181,localhost:42181
    KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS: 6000
  network_mode: host

services:
  zookeeper-1:
    <<: *zookeeper-common
    hostname: zoo-1
    environment:
      <<: *zookeeper-common-env
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 22181
    healthcheck:
      test: ["CMD", "nc", "-vz", "localhost", "22181"]
      interval: 10s
      timeout: 10s
      retries: 5

  zookeeper-2:
    <<: *zookeeper-common
    hostname: zoo-2
    environment:
      <<: *zookeeper-common-env
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 32181
    healthcheck:
      test: ["CMD", "nc", "-vz", "localhost", "32181"]
      interval: 10s
      timeout: 10s
      retries: 5

  zookeeper-3:
    <<: *zookeeper-common
    hostname: zoo-3
    environment:
      <<: *zookeeper-common-env
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 42181
    healthcheck:
      test: ["CMD", "nc", "-vz", "localhost", "42181"]
      interval: 10s
      timeout: 10s
      retries: 5

  kafka-1:
    <<: *kafka-common
    hostname: kafka-1
    environment:
      <<: *kafka-common-env
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092
      KAFKA_BROKER_ID: 1
    healthcheck:
      test: ["CMD", "nc", "-vz", "localhost", "29092"]
      interval: 10s
      timeout: 10s
      retries: 5
    depends_on:
      zookeeper-1:
        condition: service_healthy
      zookeeper-2:
        condition: service_healthy
      zookeeper-3:
        condition: service_healthy

  kafka-2:
    <<: *kafka-common
    hostname: kafka-2
    environment:
      <<: *kafka-common-env
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:39092
      KAFKA_BROKER_ID: 2
    healthcheck:
      test: ["CMD", "nc", "-vz", "localhost", "39092"]
      interval: 10s
      timeout: 10s
      retries: 5
    depends_on:
      zookeeper-1:
        condition: service_healthy
      zookeeper-2:
        condition: service_healthy
      zookeeper-3:
        condition: service_healthy

  kafka-3:
    <<: *kafka-common
    hostname: kafka-3
    environment:
      <<: *kafka-common-env
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:49092
      KAFKA_BROKER_ID: 3
    healthcheck:
      test: ["CMD", "nc", "-vz", "localhost", "49092"]
      interval: 10s
      timeout: 10s
      retries: 5
    depends_on:
      zookeeper-1:
        condition: service_healthy
      zookeeper-2:
        condition: service_healthy
      zookeeper-3:
        condition: service_healthy
